export const CACHE_TAGS = {
    EVENT_CARDS: "event_cards",
    MY_FAVOURITES: "my-favourites",
    MARKETPLACE: "marketplace",
    CATEGORIES: "categories",
    AFFILIATE_DASHBOARD: "affiliate-dashboard",
    AFFILIATE_LINKS: "affiliate-links",
    AFFILIATE_EARNINGS: "affiliate-earnings",
    AFFILIATE_PERFORMANCE_WEEK: "affiliate-performance-week",
    AFFILIATE_PERFORMANCE_MONTH: "affiliate-performance-month",
    WITHDRAWAL_HISTORY: "withdrawal-history",
    AFFILIATE_PERFORMANCE_YEAR: "affiliate-performance-year",
    HOSTS: "hosts",
    HOST_DETAILS: "host-details",
    EVENT_DETAILS: "event-details",
    PROFILE: "profile",
} as const